on: 
  push:
    tags:
      - '[0-9].[0-9]+.[0-9]+**'
  
jobs:
  selectEnvName:
    name: Select Name based on branch
    runs-on: ubuntu-latest
    outputs:
      deployEnv: ${{ steps.branchCheck.outputs.deployEnv }}
    steps:
      - id: branchCheck
        run: |
          echo "Develop Selected"
          echo "deployEnv=develop" >> $GITHUB_OUTPUT
          
      - name: Use variable setup in previous step
        run: echo "I'm using variable ${{ steps.branchCheck.outputs.deployEnv }}"

  testRunner:
    name: Test in ${{ matrix.testMode }} ✨
    runs-on: ubuntu-latest
    outputs:
      artifactsPath: ${{ steps.testRunner.outputs.artifactsPath }}
    needs: [selectEnvName]
    strategy:
      fail-fast: true
      max-parallel: 1
      matrix:
        testMode:
          - EditMode
          - PlayMode
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create LFS file list
        run: git lfs ls-files -l | cut -d' ' -f1 | sort > .lfs-assets-id

      - name: Restore LFS cache
        uses: actions/cache@v3
        id: lfs-cache
        with:
          path: .git/lfs
          key: ${{ runner.os }}-lfs-${{ hashFiles('.lfs-assets-id') }}

      - name: Git LFS Pull
        run: |
          git lfs pull
          git add .
          git reset --hard

      - name: Restore Library cache
        uses: actions/cache@v3
        with:
          path: KOTE_WebGL/Library
          key: Library-${{ matrix.targetPlatform }}
          restore-keys: |
            Library-

      - name: Run tests
        uses: game-ci/unity-test-runner@v2
        id: testRunner
        env: 
          UNITY_SERIAL: ${{ secrets.UNITY_SERIAL }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          testMode: ${{ matrix.testMode }}
          checkName: ${{ matrix.testMode }} test results
          projectPath: ${{ vars.PROJECT_PATH }}

      # Workaround for NUnit XML (see https://github.com/dorny/test-reporter/issues/98#issuecomment-867106931)
      - name: Install NUnit
        if: always()
        run: |
          nuget install NUnit.Console -Version 3.12.0

      - name: Fetch transform code
        if: always()
        run: |
          wget https://raw.githubusercontent.com/nunit/nunit-transforms/master/nunit3-junit/nunit3-junit.xslt
        shell: bash

      - name: Transform NUnit3 to JUnit
        if: always()
        run: |
          Get-ChildItem . -Filter artifacts/*.xml | Foreach-Object {
            $xml = Resolve-Path $_.FullName
            $output = Join-Path ($pwd) ($_.BaseName + '_junit.xml')
            $xslt = New-Object System.Xml.Xsl.XslCompiledTransform;
            $xslt.Load("nunit3-junit.xslt");
            $xslt.Transform($xml, $output);
          }
        shell: pwsh

      - uses: dorny/test-reporter@v1
        if: always()
        with:
          name: "unity-test-results-${{ matrix.buildTarget }}-${{ matrix.scriptingRuntime }}-${{ matrix.mode }}-${{ matrix.progress }}-${{ matrix.pooling }}"
          path: "*_junit.xml"
          reporter: java-junit

      - uses: actions/upload-artifact@v2
        if: always()
        with:
          name: unity-test-results-${{ matrix.buildTarget }}-${{ matrix.scriptingRuntime }}-${{ matrix.mode }}-${{ matrix.progress }}-${{ matrix.pooling }}
          path: artifacts

      - name: Upload Code Coverage Results
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: Coverage results (${{ matrix.testMode }})
          path: ${{ steps.testRunner.outputs.coveragePath }}

      - name: Notify Test Failure
        uses: indiesdev/curl@v1.1
        if: failure()
        with:
          url: ${{ secrets.SLACK_WEBHOOK }}
          method: "POST"
          headers: '{ "Content-type": "application/json" }'
          body: '{ "text": "GitHub Action: Test [${{ matrix.testMode }}] in environment ${{ needs.selectEnvName.outputs.deployEnv }} has failed." }'

  buildWebGL:
    name: Build Project
    runs-on: ubuntu-latest
    needs: [selectEnvName]
    outputs:
      buildVersion: ${{ steps.buildAction.outputs.buildVersion }}
    # needs: testRunner
    steps:
      - name: Notify Build Starting
        uses: indiesdev/curl@v1.1
        with:
          url: ${{ secrets.SLACK_WEBHOOK }}
          method: "POST"
          headers: '{ "Content-type": "application/json" }'
          body: '{ "text": "GitHub Action: Now building for ${{ needs.selectEnvName.outputs.deployEnv }}. This process may take several minutes." }'

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create LFS file list
        run: git lfs ls-files -l | cut -d' ' -f1 | sort > .lfs-assets-id

      - name: Restore LFS cache
        uses: actions/cache@v3
        id: lfs-cache
        with:
          path: .git/lfs
          key: ${{ runner.os }}-lfs-${{ hashFiles('.lfs-assets-id') }}

      - name: Git LFS Pull
        run: |
          git lfs pull
          git add .
          git reset --hard

      - name: Restore Library cache
        uses: actions/cache@v3
        with:
          path: KOTE_WebGL/Library
          key: Library-WebGL
          restore-keys: |
            Library-

      - name: Build Game in Unity
        id: buildAction
        uses: game-ci/unity-builder@v2
        env: 
          UNITY_SERIAL: ${{ secrets.UNITY_SERIAL }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          versioning: Tag
          targetPlatform: WebGL
          projectPath: ${{ vars.PROJECT_PATH }}
          buildsPath: build
          buildName: WebGL

      - name: Notify Build Success
        uses: indiesdev/curl@v1.1
        if: success()
        with:
          url: ${{ secrets.SLACK_WEBHOOK }}
          method: "POST"
          headers: '{ "Content-type": "application/json" }'
          body: '{ "text": "GitHub Action: Build for ${{ needs.selectEnvName.outputs.deployEnv }} was successful. Version number [${{ steps.buildAction.outputs.buildVersion }}]" }'

      - name: Notify Build Failure
        uses: indiesdev/curl@v1.1
        if: failure()
        with:
          url: ${{ secrets.SLACK_WEBHOOK }}
          method: "POST"
          headers: '{ "Content-type": "application/json" }'
          body: '{ "text": "GitHub Action: Build for ${{ needs.selectEnvName.outputs.deployEnv }} has failed. Please visit the GitHub Repository for more information." }'

      - uses: actions/upload-artifact@v2
        with:
          name: build-WebGL
          path: build/WebGL/WebGL


  deployToDev:
    name: Deploy to dev
    needs: [buildWebGL, selectEnvName]
    environment: ${{ needs.selectEnvName.outputs.deployEnv }}
    runs-on: ubuntu-latest
    steps:

    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Download WebGL Artifact
      uses: actions/download-artifact@v2
      with:
        name: build-WebGL
        path: "${{ vars.BUILD_DIRECTORY }}"

    - name: Notify Push to Server
      uses: indiesdev/curl@v1.1
      with:
        url: ${{ secrets.SLACK_WEBHOOK }}
        method: "POST"
        headers: '{ "Content-type": "application/json" }'
        body: '{ "text": "GitHub Action: Now pushing to ${{ needs.selectEnvName.outputs.deployEnv }} [${{ steps.buildAction.outputs.buildVersion }}]. The server may be down for upto 5 minutes." }'

    - name: Deploy to server
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key : ${{ secrets.SSH_PRIV_KEY }}
        source: "${{ vars.BUILD_DIRECTORY }}"
        target: "${{ vars.PUBLISH_PATH }}"
        overwrite: true

    - name: Notify Push Success
      uses: indiesdev/curl@v1.1
      if: success()
      with:
        url: ${{ secrets.SLACK_WEBHOOK }}
        method: "POST"
        headers: '{ "Content-type": "application/json" }'
        body: '{ "text": "GitHub Action: Push to ${{ needs.selectEnvName.outputs.deployEnv }} [${{ steps.buildAction.outputs.buildVersion }}] is successful." }'
      
    - name: Notify Push Failure
      uses: indiesdev/curl@v1.1
      if: failure()
      with:
        url: ${{ secrets.SLACK_WEBHOOK }}
        method: "POST"
        headers: '{ "Content-type": "application/json" }'
        body: '{ "text": "GitHub Action: Push to ${{ needs.selectEnvName.outputs.deployEnv }} [${{ steps.buildAction.outputs.buildVersion }}] has failed. Please vist the GitHub Repository for more information." }'
