on: 
  workflow_dispatch:
  
jobs:
  downloadFromLastBranch:
    name: Download from Stage
    environment: staging
    runs-on: ubuntu-latest
    steps:

    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Notify Pull from Stage
      uses: indiesdev/curl@v1.1
      with:
        url: ${{ secrets.SLACK_WEBHOOK }}
        method: "POST"
        headers: '{ "Content-type": "application/json" }'
        body: '{ "text": "GitHub Action: Now pulling from Stage for promotion to Alpha." }'

    - run: mkdir ./build

    - name: Download Build from Stage
      uses: alinz/ssh-scp-action@master
      with:
        host: ${{ secrets.HOST }}
        user: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_PRIV_KEY }}
        scp: |
          -r ${{ secrets.USERNAME }}@${{ secrets.HOST }}:${{ vars.PUBLISH_PATH }}/${{ vars.BUILD_DIRECTORY }} ./build

    - name: Upload build as artifact
      uses: actions/upload-artifact@v2
      with:
        name: build-WebGL
        path: ./build/${{ vars.BUILD_DIRECTORY }}

    - name: Notify Pull Success
      uses: indiesdev/curl@v1.1
      if: success()
      with:
        url: ${{ secrets.SLACK_WEBHOOK }}
        method: "POST"
        headers: '{ "Content-type": "application/json" }'
        body: '{ "text": "GitHub Action: Pull from Stage was successful!" }'

    - name: Notify Push Failure
      uses: indiesdev/curl@v1.1
      if: failure()
      with:
        url: ${{ secrets.SLACK_WEBHOOK }}
        method: "POST"
        headers: '{ "Content-type": "application/json" }'
        body: '{ "text": "GitHub Action: Pull from Stage has failed. Could not update Alpha. Please vist the GitHub Repository for more information." }'

  uploadToAlpha:
    name: Upload to Alpha
    needs: downloadFromLastBranch
    environment: alpha
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Download WebGL Artifact
      uses: actions/download-artifact@v2
      with:
        name: build-WebGL
        path: "${{ vars.BUILD_DIRECTORY }}"

    - name: Notify Push to Server
      uses: indiesdev/curl@v1.1
      with:
        url: ${{ secrets.SLACK_WEBHOOK }}
        method: "POST"
        headers: '{ "Content-type": "application/json" }'
        body: '{ "text": "GitHub Action: Now pushing to Alpha. The server may be down for upto 5 minutes." }'

    - name: Deploy to server
      uses: reggionick/s3-deploy@v3
      with:
        folder: "${{ vars.BUILD_DIRECTORY }}"
        bucket: ${{ vars.S3_BUCKET }}
        bucket-region: ${{ vars.S3_BUCKET_REGION }}

    - name: Notify Push Success
      uses: indiesdev/curl@v1.1
      if: success()
      with:
        url: ${{ secrets.SLACK_WEBHOOK }}
        method: "POST"
        headers: '{ "Content-type": "application/json" }'
        body: '{ "text": "GitHub Action: Push to Alpha is successful." }'
      
    - name: Notify Push Failure
      uses: indiesdev/curl@v1.1
      if: failure()
      with:
        url: ${{ secrets.SLACK_WEBHOOK }}
        method: "POST"
        headers: '{ "Content-type": "application/json" }'
        body: '{ "text": "GitHub Action: Push to Alpha has failed. Please vist the GitHub Repository for more information." }'

    - name: Delete Artifacts
      uses: geekyeggo/delete-artifact@v2
      if: always()
      with:
        name: build-WebGL
