on: workflow_dispatch

jobs:
  selectEnvName:
    name: Select Name based on branch
    runs-on: ubuntu-latest
    outputs:
      env_name: ${{ steps.branch_check.outputs.env_name }}
    steps:
      - name: Determine deploy environment
        id: branch-check
        run: |
          if [ "${{ github.ref }}" == "refs/heads/releases/dev" ]; then
            echo "env_name=develop" >> $GITHUB_OUTPUT
          elif [ "${{ github.ref }}" == "refs/heads/releases/stage" ]; then
            echo "env_name=stage" >> $GITHUB_OUTPUT
          elif [ "${{ github.ref }}" == "refs/heads/releases/alpha" ]; then
            echo "env_name=alpha" >> $GITHUB_OUTPUT
          else
            echo "env_name=develop" >> $GITHUB_OUTPUT
          fi
        
      - name: Use variable setup in previous step
        run: echo "I'm using variable ${{ selectEnvName.outputs.env_name }}"

  displayEnvName:
    name: Display Environment Name
    runs-on: ubuntu-latest
    needs: selectEnvName
    steps:
      - run: echo echo "I got ${{ needs.selectEnvName.outputs.env_name }}"
    
