on: workflow_dispatch

jobs:
  selectEnvName:
    name: Select Name based on branch
    runs-on: ubuntu-latest
    steps:
      - name: Determine deploy environment
        id: branch-check
        run: |
          if [ "${{ github.ref }}" = "refs/heads/releases/dev" ]; then
            echo "env_name=develop" >> $GITHUB_OUTPUT
          elif [ "${{ github.ref }}" = "refs/heads/releases/stage" ]; then
            echo "env_name=stage" >> $GITHUB_OUTPUT
          elif [ "${{ github.ref }}" = "refs/heads/releases/alpha" ]; then
            echo "env_name=alpha" >> $GITHUB_OUTPUT
          else
            echo "env_name=develop" >> $GITHUB_OUTPUT
          fi
        
      - name: Use variable setup in previous step
        run: echo "I'm using variable ${{ steps.branch_check.outputs.env_name }}"