on: workflow_dispatch

jobs:
  selectEnvName:
    name: Select Name based on branch
    runs-on: ubuntu-latest
    outputs:
      env_name: ${{ steps.branch_check.outputs.env_name }}
    steps:
      - name: Determine deploy environment
        id: branch-check
        run: |
          if [ "${{ github.ref }}" == "refs/heads/releases/dev" ]; then
            echo "Develop Selected"
            echo "env_name=develop" >> $GITHUB_OUTPUT
          elif [ "${{ github.ref }}" == "refs/heads/releases/stage" ]; then
            echo "Stage Selected"
            echo "env_name=stage" >> $GITHUB_OUTPUT
          elif [ "${{ github.ref }}" == "refs/heads/releases/alpha" ]; then
            echo "Alpha Selected"
            echo "env_name=alpha" >> $GITHUB_OUTPUT
          else
            echo "Else Fired, Manual run of workflow goes to develop"
            echo "env_name=develop" >> $GITHUB_OUTPUT
          fi

  displayEnvName:
    name: Display Environment Name
    runs-on: ubuntu-latest
    needs: selectEnvName
    steps:
      - run: echo echo "I got ${{ needs.selectEnvName.outputs.env_name }}"
    
